### ISSUE TITLE
A variation of `show-relation` to display description instead of relation data

### ISSUE THREAD

**Issue by sed-i** [canonical/jhack#193]
In metadata, charm authors can include a description per relation, for example:

```yaml
  certificates:
    interface: tls-certificates
    limit: 1
    description: |
      Certificate and key files for the alertmanager server to use to authenticate to client.
```

In a model, for every integration between two charms, jhack could pull the `description` field for that same relation from both charms. This could give a nice functional overview of model internals.
