### ISSUE TITLE
`jhack audit`?

### ISSUE THREAD

**Issue by sed-i** [canonical/jhack#194]
Currently, juju audit information is spread across `show-status-log --format=json`, `debug-log`.

It would be handy if jhack could augment/restructure/filter it into an audit log that addresses a separate use case. Perhaps something like:

```bash
$ jhack audit --aggregate-by=application-name
```
```yaml
"traefik-k8s/trfk":
  - time: "09 Oct 2024 16:50:40-00:00"
    event: deploy
  - time: "09 Oct 2024 16:50:42-00:00"
    event: integrate
    endpoints: [trfk:ingress-per-app, am:ingress]
  - time: ""09 Oct 2024 16:50:43-00:00"
    event: config-changed
    # no need to list relation-changed events here because it's implementation detail
    # from a model audit perspective, relation created+removed and config changed should be enough?
```

I don't have a spec, but the above are some preliminary requirements I could think of.
